In [36]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [21]:
data = pd.read_csv("/kaggle/input/microsoft-lifetime-stocks-dataset/MSFT.csv")

In [22]:
data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

# pre processing

In [26]:
#Remove the Date column because it doesn't have any significance

data = data.drop(["Date"] ,axis=1)

In [27]:
# checking for null values
null_counts = data.isnull()
null_counts.sum()

Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

normalize data

In [40]:
scaler = MinMaxScaler(feature_range =(0,1))
dataset = pd.DataFrame(scaler.fit_transform(data), columns = data.columns)
dataset

          Open      High       Low     Close  Adj Close    Volume
0     0.000000  0.000059  0.000000  0.000043   0.000028  1.000000
1     0.000054  0.000065  0.000055  0.000065   0.000042  0.297096
2     0.000076  0.000070  0.000077  0.000076   0.000049  0.127119
3     0.000087  0.000070  0.000066  0.000059   0.000038  0.063588
4     0.000071  0.000054  0.000055  0.000049   0.000031  0.044285
...        ...       ...       ...       ...        ...       ...
8520  0.983183  0.981574  0.988119  0.981810   0.981814  0.015605
8521  0.995796  1.000000  1.000000  1.000000   1.000000  0.019736
8522  0.992909  0.995144  0.998294  0.987541   0.987544  0.018273
8523  0.985128  0.989853  0.988499  0.990095   0.990097  0.017980
8524  0.999184  0.993401  0.993681  0.981063   0.981067  0.015264

[8525 rows x 6 columns]

**TRAIN TEST SPLIT**

In [38]:
X = dataset.drop(["High"] , axis = 1)
Y = dataset["High"]

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,Y)